### ISSUE TITLE
GW analysis on Renku

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/dispatcher-plugin-gw#10]
I tried to push "publish on Renku" button, it openss the Jupiter, but then if I try to run the API code, I see some display of an html in the response, not the data product in a "digestible" format.....

**Comment by volodymyrss** [comment]
it's because staging is extra protected by github auth. We do not put a suitable access mechanism in the API code, since we do not need it in production. 
We could add logic in the API code generation learning if it's in cookie-protected place.
Or it could be added manually.

edit: if you want to test with cookie, let me know, but it's some effort for the user.  
else we just  check that the code makes sense, and will see the production.
if you want to check the API from inside UNIGE, try this for dispatcher: https://frontend-staging.obsuks1.unige.ch/mmoda/dispatch-data/

**Comment by volodymyrss** [comment]
please reopen if unclear
